name: Front End Feature
description: This is not for suggested features, this is for James and Lead Devs to create issues for features that have been discussed and agreed upon.
labels: ['Feature']
title: "[Feature][FE] - Issue Title...."
body:
  - type: input
    id: figma-link
    attributes:
      label: Figma Link (if applicable)
      description: Provide a link to the Figma design, if available.
      placeholder: "https://www.figma.com/file/..."   
  - type: input
    id: sister-branch
    attributes:
      label: BE sister branch (if applicable)
      description: Please specify the sister back-end (BE) branch name or link..
      placeholder: "Nabil-230443-Fix-Bug...."   
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: What are the specific conditions or outcomes that the code must satisfy to be considered complete and ready for deployment?
      placeholder: "- [ ] Confirm that buttons display updated icons as per design."
    validations:
      required: true  
  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: What are the specific conditions or criteria that must be met, including passing Quality Assurance (Q/A), to consider the testing plan complete and ready for deployment to the development server?
      placeholder: "- [ ] Verify that all responsive design breakpoints are functioning correctly."
    validations:
      required: true  
  - type: textarea
    id: photos
    attributes:
      label: Photos/Screenshots
      description: Please upload any relevant images or screenshots to help illustrate the feature here.

    
