name: Frontend Feature Request
description: Create a frontend feature request
title: "[Feature] Issue Title"
body:
- type: markdown
  attributes:
    value: >
      Thank you for submitting a frontend feature request! Before you proceed, please check existing issues to avoid duplicates.

      **Feature Details:**
- type: textarea
  id: feature-details
  attributes:
    label: Feature Details
    description: Provide a clear and concise description of the frontend feature.
    placeholder: Describe the feature...

- type: input
  id: epic-title
  attributes:
    label: Epic Title (if applicable)
    description: Link to the corresponding Epic, if this feature is part of one.
    placeholder: Link to Epic...

- type: input
  id: figma-link
  attributes:
    label: Figma Link (if applicable)
    description: Provide a link to the Figma design, if available.
    placeholder: Link to Figma...

- type: markdown
  attributes:
    value: |
      **Acceptance Criteria:**

      Use the checklist below to specify the acceptance criteria for this feature. Add or remove items as needed.
- type: checklist
  id: acceptance-criteria
  attributes:
    options:
      - label: Criteria 1
        required: true
      - label: Criteria 2
      - label: Criteria 3

- type: textarea
  id: feature-description
  attributes:
    label: Feature Description
    description: Provide a detailed description of the frontend feature's purpose and functionality.
    placeholder: Describe the feature in detail...

- type: markdown
  attributes:
    value: |
      **Photos:**

      You can upload any relevant images or screenshots to help illustrate the feature.
- type: input
  id: photo-upload
  attributes:
    label: Photo Upload
    description: Attach images or screenshots (if applicable)
    placeholder: Attach files...

labels:
  - Feature
