name: Label Management

on:
  project_card:
    types:
      - moved

jobs:
  label-management:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any Python dependencies

    - name: Calculate duration and manage labels
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python label_management.py
